language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3

gemfile:
  - gemfiles/rails2.3.gemfile
  - gemfiles/rails3.0.gemfile
  - gemfiles/rails3.1.gemfile
  - gemfiles/rails3.2.gemfile

script: "bundle install && bundle exec rake test"
